name: Melon Ticket Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  ticket-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: npm install

      - name: Build
        run: npx tsc

      - name: Run
        run: node dist/index.js
        env:
          INPUT_COOKIE: ${{ secrets.MELON_COOKIE }}
          INPUT_PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
          INPUT_SCHEDULE_ID: ${{ secrets.SCHEDULE_ID }}
