name: Melon Ticket Action
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ticket-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g ts-node typescript

      - name: Run Script
        run: ts-node index.ts
        env:
          COOKIE: ${{ secrets.MELON_COOKIE }}
          PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
          SCHEDULE_ID: ${{ secrets.SCHEDULE_ID }}
          INPUT_COOKIE: ${{ secrets.MELON_COOKIE }}
          INPUT_PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
          INPUT_SCHEDULE_ID: ${{ secrets.SCHEDULE_ID }}
